name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      env:
        KERNEL: 4.4
      run: |
        if [ $KERNEL = "4.4" ] ; then
        git clone --depth=1 https://github.com/aceboy50/bongo-net.git /opt/rt-n56u
        else
        git clone --depth=1 https://github.com/aceboy50/Padavan.git /opt/rt-n56u
        fi
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: MI-R4AG
        KERNEL: 4.4
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        ################################################################################################
        #Since the configuration functions of different models are different, delete the configuration items first. 
        #If you want to add other items yourself, you should also write and delete this item, remember! ! !
        ################################################################################################
        #Crappy OpenSSL-related things, ppl using Padavan might not want it
        sed -i '/CONFIG_FIRMWARE_INCLUDE_EAP_PEAP/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HTTPS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SFTP/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DROPBEAR/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DROPBEAR_FAST_CODE/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENSSH/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENVPN/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSWAN/d' .config #StrongSwan is IPSec MultiClient
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EC/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION/d' .config #Torrent Client
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA/d' .config #Downloader Client, Jdownloader better :P
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL/d' .config
        #These are customs configuration for AIO lover, some like but others don't
        sed -i '/CONFIG_FIRMWARE_INCLUDE_CURL/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #Delete SCUTCLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' .config #Delete DOGCOM battery
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIEAP/d' .config #Delete MENTOHUST related
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT/d' .config #Delete what i know nothing about it
        sed -i '/CONFIG_FIRMWARE_INCLUDE_VLMCSD/d' .config #Delete virtual KMS server
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HTOP/d' .config #Delete CLI Task manager
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NANO/d' .config #I started to liek the VI command more
        sed -i '/CONFIG_FIRMWARE_INCLUDE_IPERF3/d' .config #This is a speed testing tool
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #Delete MENTOHUST
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOCAT/d' .config #Delete Proxy related
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config #Delete Proxy client
        sed -i '/CONFIG_FIRMWARE_INCLUDE_WIREGUARD/d' .config #Delete Wireguard
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #Delete SS plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #Delete SS server
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #Delete DNSFORWARDER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config #Delete adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config #Delete adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config #Delete adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config #Delete adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config #Delete AliDDNS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config #Delete Smart DDNS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TROJAN/d' .config #Delete Trojan- Chinese GFW bypassing tool
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        ######################################################################
        #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
        ######################################################################
        if [ $KERNEL = "4.4" ] ; then
        #Newlythings
        echo "CONFIG_FIRMWARE_INCLUDE_EAP_PEAP=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_HTTPS=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SFTP=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_DROPBEAR=y" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_DROPBEAR_FAST_CODE=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_OPENSSH=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_OPENVPN=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SSWAN=n" >> .config #StrongSwan is IPSec MultiClient
        echo "CONFIG_FIRMWARE_INCLUDE_OPENSSL_EC=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_TRANSMISSION=n" >> .config #Torrent Client
        echo "CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_ARIA=n" >> .config #Downloader Client, Jdownloader better :P
        echo "CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL=n" >> .config
        #REmaining
        echo "CONFIG_FIRMWARE_INCLUDE_CURL=n" .config
        echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config #Delete SCUTCLIENT
        echo "CONFIG_FIRMWARE_INCLUDE_DOGCOM=n" >> .config #Delete DOGCOM battery
        echo "CONFIG_FIRMWARE_INCLUDE_MINIEAP=n" >> .config #Delete MENTOHUST related
        echo "CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=n" >> .config #Delete what i know nothing about it
        echo "CONFIG_FIRMWARE_INCLUDE_VLMCSD=n" >> .config #Delete virtual KMS server
        echo "CONFIG_FIRMWARE_INCLUDE_HTOP=n" >> .config #Delete CLI Task manager
        echo "CONFIG_FIRMWARE_INCLUDE_NANO=n" >> .config #I started to liek the VI command more
        echo "CONFIG_FIRMWARE_INCLUDE_IPERF3=n" >> .config #This is a speed testing tool
        echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #MENTOHUST
        echo "CONFIG_FIRMWARE_INCLUDE_SOCAT=n" .config #Proxy related
        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config #Can't be intergrated
        echo "CONFIG_FIRMWARE_INCLUDE_WIREGUARD=n"  >> .config #wireguard
        echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config #SCUTCLIENT
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> .config #SS plus+
        echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=n" >> .config # simple-obfs
        echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=n" >> .config #adbyby plus+
        echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #DNSFORWARDER
        echo "CONFIG_FIRMWARE_INCLUDE_XRAY=n" >> .config #xray  ~4.5M
        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config #v2ray
        echo "CONFIG_FIRMWARE_INCLUDE_DDNSTO=n" >> .config #ddnsto  ~0.5M
        echo "CONFIG_FIRMWARE_INCLUDE_ALDRIVER=n" >> .config  #Aliyun Cloud Disk  ~3m
        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config #zerotier ~1.3M
        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config #aliddns
        echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n" >> .config #Adguard Home
        echo "CONFIG_FIRMWARE_INCLUDE_SQM=n"  >> .config #sqm Remember that SQM will affects the HWNAT Offloading Function!
        echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=n" >> .config #Integrate trojan execution file  1.2M
        else
        #Those things are kernel 3 padavan, i dont like it. Too unstable for new driver/routers
        echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #MENTOHUST
        echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config #SCUTCLIENT
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> .config #SS plus+
        echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=n" >> .config # simple-obfs混淆插件
        echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config #SS server
        echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #DNSFORWARDER
        echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=y" >> .config #adbyby plus+
        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> .config #内网穿透FRPC
        echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config #内网穿透FRPS
        echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config #TUNSAFE
        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=y" >> .config #阿里DDNS
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y" >> .config #smartdns
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=y" >> .config #smartdns二进制文件
        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=y" >> .config #集成v2ray执行文件（3.8M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
        echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=n" >> .config #集成trojan执行文件(1.1M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
        echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=y" >> .config #KP广告过滤
        echo "CONFIG_FIRMWARE_INCLUDE_CADDY=y" >> .config #在线文件管理服务
        echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config #集成caddu执行文件，此文件有13M,请注意固件大小。如果不集成，会从网上下载下来执行，不影响正常使用
        echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=y" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config #可以不集成
        echo "CONFIG_FIRMWARE_INCLUDE_WYY=y" >> .config #网易云解锁
        echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> .config #网易云解锁GO版本执行文件（4M多）注意固件超大小,不集成会自动下载
        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config #zerotier ~1.3M
        fi
        #########################################################################################
        #For custom settings please add to this file lines at configs/templates/.config following the formula above.
        #For example：
        #sed -i '/CONFIG_FIRMWARE_INCLUDE_XXX/d' .config
        #echo "CONFIG_FIRMWARE_INCLUDE_XXX=y/n" >> .config
        #########################################################################################
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
