name: Build FlaOS-Padavan (Revamped)

on: 
  push:
    branches:
    - '*'
  workflow_dispatch:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      matrix:
        target: [MI-R3P]
        toolchain: [mipsel-linux-musl]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Cache 
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ matrix.target }}-${{ matrix.toolchain }}
    - name: Golang
      uses: actions/setup-go@v4
      with:
          go-version: '1.20'
          check-latest: true
          cache: false
    - name: Setup node      
      uses: actions/setup-node@v3
      with:
          node-version: 18
          check-latest: true
    - name: Initialization environment
      run: |
          sudo apt update
          sudo apt install libtool-bin gperf python3-docutils autopoint gettext ccache
    - name: Build
      run: |
          sed -i 's/CONFIG_FIRMWARE_INCLUDE_LANG_CN/CONFIG_FIRMWARE_INCLUDE_LANG_VI/g' trunk/configs/templates/${{ matrix.target }}.config
          make ${{ matrix.target }} TOOLCHAIN=${{ matrix.toolchain }}
          if [ "${{ matrix.target }}" = "K2P-NANO" ]; then
            image=$(ls trunk/images/*.trx)
            mv $image $(echo $image | sed 's/K2P/K2P-NANO/')
          fi
    - uses: actions/upload-artifact@v3
      with:
          name: ${{ matrix.toolchain }}
          path: trunk/images/*.trx
  publish:
    needs: [build]
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Set Tag Name
        run: echo "TAG_ANME=$(date +%Y%m%d)" >> $GITHUB_ENV
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.TAG_ANME }}
          force_push_tag: true
      - uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.sha }}
          tag: ${{ env.TAG_ANME }}
          artifacts: "mipsel-linux-musl/*.trx"
          allowUpdates: true
